jobs: Properly json encode the results in case of errors
In case of internal errors, we were getting:

| Job failed: InternalError: Command "flatpak" "build-commit-from" "--force" "--no-update-summary" "--gpg-homedir=/vcs/gnome/flathub/gpg" "--gpg-sign=01DA958A7DC283BF1D3D208CF154092B3A7124D7" "--src-repo=build-repo/573" "repo" exited unsuccesfully: error: Writing content object: fchown: Operation not permitted
|
\ Job failed
Unexpected JSONDecodeError exception in push: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "./flat-manager-client", line 720, in <module>
    result = loop.run_until_complete(args.func(args))
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "./flat-manager-client", line 558, in push_command
    reparse_job_results(publish_job)
  File "./flat-manager-client", line 301, in reparse_job_results
    job["results"] = json.loads(job.get("results", "{}"))
  File "/usr/lib64/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

This is due to the results field in the jobresult just being the error string, while its supposed to be a
stringified json object.